version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: zexagres
      POSTGRES_PASSWORD: 1337
      POSTGRES_DB: mymynest
    networks:
      - zxvl
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: zexagres
      POSTGRES_PASSWORD: 1337
      POSTGRES_DB: mymynest
    networks:
      - zxvl
networks:
  zxvl: